# Generated by Django 4.0.4 on 2022-06-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otherworldsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(max_length=200)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='otherworldsapi.world')),
            ],
        ),
    ]
