# Generated by Django 4.0.4 on 2022-06-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherworldsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date_suffix',
            field=models.CharField(default='CE', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.IntegerField(),
        ),
    ]
