# Generated by Django 4.0.4 on 2022-06-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otherworldsapi', '0002_events_date_suffix_alter_events_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otherworldsapi.events')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otherworldsapi.world')),
            ],
        ),
    ]
