# Generated by Django 4.0.4 on 2022-06-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otherworldsapi', '0003_worldevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldEvent',
        ),
    ]
