# Generated by Django 4.0.4 on 2022-06-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherworldsapi', '0003_alter_map_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map',
            field=models.TextField(),
        ),
    ]
