# Generated by Django 4.0.4 on 2022-06-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otherworldsapi', '0004_alter_map_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='map',
            new_name='map_image',
        ),
    ]
