# Generated by Django 4.0.4 on 2022-06-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherworldsapi', '0004_delete_worldevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='biome',
        ),
        migrations.AddField(
            model_name='region',
            name='biome',
            field=models.ManyToManyField(related_name='region', to='otherworldsapi.biome'),
        ),
    ]
