# Generated by Django 4.0.5 on 2022-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherworldsapi', '0005_rename_map_map_map_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='description',
            field=models.TextField(),
        ),
    ]
