# Generated by Django 4.0.5 on 2022-06-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherworldsapi', '0006_alter_region_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='description',
            field=models.TextField(),
        ),
    ]
